/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAlertsRouteImport } from './routes/app.alerts'
import { Route as AppAskRouteImport } from './routes/app.ask'
import { Route as AppAuditRouteImport } from './routes/app.audit'
import { Route as AppBillsRouteImport } from './routes/app.bills'
import { Route as AppCarbonRouteImport } from './routes/app.carbon'
import { Route as AppEnergyRouteImport } from './routes/app.energy'
import { Route as AppRecommendationsRouteImport } from './routes/app.recommendations'
import { Route as AppReportsRouteImport } from './routes/app.reports'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppAskRoute = AppAskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppBillsRoute = AppBillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => AppRoute,
} as any)
const AppCarbonRoute = AppCarbonRouteImport.update({
  id: '/carbon',
  path: '/carbon',
  getParentRoute: () => AppRoute,
} as any)
const AppEnergyRoute = AppEnergyRouteImport.update({
  id: '/energy',
  path: '/energy',
  getParentRoute: () => AppRoute,
} as any)
const AppRecommendationsRoute = AppRecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/ask': typeof AppAskRoute
  '/app/audit': typeof AppAuditRoute
  '/app/bills': typeof AppBillsRoute
  '/app/carbon': typeof AppCarbonRoute
  '/app/energy': typeof AppEnergyRoute
  '/app/recommendations': typeof AppRecommendationsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/ask': typeof AppAskRoute
  '/app/audit': typeof AppAuditRoute
  '/app/bills': typeof AppBillsRoute
  '/app/carbon': typeof AppCarbonRoute
  '/app/energy': typeof AppEnergyRoute
  '/app/recommendations': typeof AppRecommendationsRoute
  '/app/reports': typeof AppReportsRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/ask': typeof AppAskRoute
  '/app/audit': typeof AppAuditRoute
  '/app/bills': typeof AppBillsRoute
  '/app/carbon': typeof AppCarbonRoute
  '/app/energy': typeof AppEnergyRoute
  '/app/recommendations': typeof AppRecommendationsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/alerts'
    | '/app/ask'
    | '/app/audit'
    | '/app/bills'
    | '/app/carbon'
    | '/app/energy'
    | '/app/recommendations'
    | '/app/reports'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/alerts'
    | '/app/ask'
    | '/app/audit'
    | '/app/bills'
    | '/app/carbon'
    | '/app/energy'
    | '/app/recommendations'
    | '/app/reports'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/alerts'
    | '/app/ask'
    | '/app/audit'
    | '/app/bills'
    | '/app/carbon'
    | '/app/energy'
    | '/app/recommendations'
    | '/app/reports'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/alerts': {
      id: '/app/alerts'
      path: '/alerts'
      fullPath: '/app/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ask': {
      id: '/app/ask'
      path: '/ask'
      fullPath: '/app/ask'
      preLoaderRoute: typeof AppAskRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/audit': {
      id: '/app/audit'
      path: '/audit'
      fullPath: '/app/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bills': {
      id: '/app/bills'
      path: '/bills'
      fullPath: '/app/bills'
      preLoaderRoute: typeof AppBillsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/carbon': {
      id: '/app/carbon'
      path: '/carbon'
      fullPath: '/app/carbon'
      preLoaderRoute: typeof AppCarbonRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/energy': {
      id: '/app/energy'
      path: '/energy'
      fullPath: '/app/energy'
      preLoaderRoute: typeof AppEnergyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/recommendations': {
      id: '/app/recommendations'
      path: '/recommendations'
      fullPath: '/app/recommendations'
      preLoaderRoute: typeof AppRecommendationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAlertsRoute: typeof AppAlertsRoute
  AppAskRoute: typeof AppAskRoute
  AppAuditRoute: typeof AppAuditRoute
  AppBillsRoute: typeof AppBillsRoute
  AppCarbonRoute: typeof AppCarbonRoute
  AppEnergyRoute: typeof AppEnergyRoute
  AppRecommendationsRoute: typeof AppRecommendationsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlertsRoute: AppAlertsRoute,
  AppAskRoute: AppAskRoute,
  AppAuditRoute: AppAuditRoute,
  AppBillsRoute: AppBillsRoute,
  AppCarbonRoute: AppCarbonRoute,
  AppEnergyRoute: AppEnergyRoute,
  AppRecommendationsRoute: AppRecommendationsRoute,
  AppReportsRoute: AppReportsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
